project:
  type: website

website:
  title: "tRNA-seq logistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - background.qmd  
      - sequencing-settings.qmd
      - library-structures.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



